[docker]

configs = [
    "selenium/standalone-firefox:4.18.1-20240224", '{"browserName": "firefox"}',
    "selenium/standalone-chrome:4.18.1-20240224", '{"browserName": "chrome"}',
    "selenium/standalone-edge:4.18.1-20240224", '{"browserName": "MicrosoftEdge"}'
]
url = "http://127.0.0.1:2375"

video-image = "selenium/video:ffmpeg-6.1-20240224"