name: On push regression tests

on: [push]

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List contents of the directory
        run: ls -la framework/healenium

      - name: Start Docker Compose Selenoid
        run: docker-compose -f framework/healenium/docker-compose-selenoid.yaml up -d

      - name: Check Docker containers status
        run: docker ps -a

      - name: Checkout again
        uses: actions/checkout@v1

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Collect only before tests
        run: pytest --collect-only

      - name: Run pytest tests
        run: pytest -s -v

      - name: Generate Allure results
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
