name: On push regression tests

on: [ push ]

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout again
        uses: actions/checkout@v1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Collect only
        run: pytest --collect-only



